---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role edx_themes
# 
dependencies:
  - role: add_user
    user_name: "{{ themes_user }}"
    user_home: "{{ themes_home }}"
    group_name: "{{ themes_user }}"
  - role: git_clone
    repo_owner: "{{ themes_user }}"
    repo_group: "{{ themes_user }}"
    GIT_REPOS: "{{ THEMES_REPOS }}"
    git_home: "{{ themes_home }}"
