- name: Deploy neo4j for coursegraph
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    CLUSTER_NAME: 'coursegraph'
  roles:
    - role: nginx
      nginx_sites:
        - coursegraph
      nginx_default_sites:
        - coursegraph
#    - aws
    - neo4j
