---
#
#  Adds the latest stable package of neo4j community edition
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role neo4j
#

#
# vars are namespaced with the module name.
#
neo4j_role_name: neo4j

neo4j_gpg_key_url: https://debian.neo4j.org/neotechnology.gpg.key
neo4j_apt_repository: "deb http://debian.neo4j.org/repo stable/"
neo4j_server_config_file: "/etc/neo4j/neo4j-server.properties"
neo4j_https_port: 8081  # default is 7473
neo4j_http_port: 8080  # default is 7474

